// Las empanadas: los GobbleGum de Black Ops 3, pero salen del horno de barro
// (entities/Empanadas.js) en vez de una máquina de chicles. Cada una es de un
// sabor distinto y trae un efecto bueno.
//
// kind:
//   'clasica'  = se desbloquea con el nivel (`level`) y no se gasta nunca.
//   'especial' = se gasta una cada vez que el horno la entrega. Solo sale en
//                la pulpería (core/progress: megas, useMega), y su `rarity`
//                pesa en los tachos: 'comun' | 'rara' | 'ultra'. Las más
//                fuertes llevan `level`: salen en la pulpería a cualquier
//                nivel, pero se usan recién desde ese.
// use (cómo se usa, como los chicles):
//   'auto'   = hace efecto al comerla. Si espera algo (el próximo mate de la
//              caja, caer...), queda en el HUD hasta que pase; `dur` es cuántas veces.
//   'tiempo' = dura `dur` segundos.
//   'rondas' = dura `dur` rondas (la de ahora cuenta).
//   'activa' = queda en la mano: se usa con la tecla de la empanada (B), `dur`
//              veces. Si cada uso dura, `secs`.
// color: el del cartelito y el aro del HUD.
// look: cómo es la empanada (weapons/empanadaModels.js):
//   shape: el repulgue. 'trenza' (el criollo, de carne), 'fino' (muchos
//          pliegues chiquitos: salteña, tucumana), 'tenedor' (cerrada con el
//          tenedor), 'parada' (el repulgue arriba, como la humita), 'triangulo'
//          (la árabe, tres costuras), 'pico' (la de pollo, con el piquito),
//          'bolsita' (atada arriba), 'sobre' (cuatro puntas al medio),
//          'redonda' (dos tapas, cerrada con tenedor todo alrededor).
//   cook:  'horno' (pintada con huevo), 'frita', 'barro' (del horno de barro,
//          con partes quemadas), 'palida' (la árabe, apenas dorada).
//   mark:  lo que la distingue arriba: 'aji' (puntito rojo), 'azucar',
//          'aceituna', 'queso' (gratinado), 'cortes' (tajitos), 'sesamo',
//          'verdeo', 'tomate'. fill: el color del relleno (se ve al morderla).

export const EMPANADAS = [
  // ---------------- clásicas ----------------
  {
    id: 'carne',
    sabor: 'Carne cortada a cuchillo',
    name: 'Al Toque',
    kind: 'clasica',
    rarity: 'comun',
    level: 1,
    use: 'rondas',
    dur: 3,
    desc: 'Apuntás y sacás el mate el doble de rápido.',
    color: '#c0552a',
    look: { shape: 'trenza', cook: 'horno', fill: '#6a3a22' },
  },
  {
    id: 'jyq',
    sabor: 'Jamón y queso',
    name: 'A Cuenta',
    kind: 'clasica',
    rarity: 'comun',
    level: 1,
    use: 'tiempo',
    dur: 180,
    desc: 'Tirás de la reserva sin cebar: mientras quede, no hace falta recargar.',
    color: '#e88aa0',
    look: { shape: 'tenedor', cook: 'horno', fill: '#f0c8b8' },
  },
  {
    id: 'humita',
    sabor: 'Humita',
    name: 'Ni Me Vieron',
    kind: 'clasica',
    rarity: 'comun',
    level: 1,
    use: 'activa',
    dur: 2,
    secs: 10,
    desc: 'Los muertos no te ven por 10 segundos. Dos usos.',
    color: '#e8c53a',
    look: { shape: 'parada', cook: 'horno', fill: '#f2d45a' },
  },
  {
    id: 'saltena',
    sabor: 'Salteña',
    name: 'Facón Afilado',
    kind: 'clasica',
    rarity: 'comun',
    level: 1,
    use: 'tiempo',
    dur: 150,
    desc: 'El facón pega cinco veces más fuerte.',
    color: '#c83a2a',
    look: { shape: 'fino', cook: 'horno', mark: 'aji', fill: '#7a3a1e', tint: '#d0602a' },
  },
  {
    id: 'pollo',
    sabor: 'Pollo',
    name: 'Me Rajo',
    kind: 'clasica',
    rarity: 'comun',
    level: 1,
    use: 'activa',
    dur: 2,
    desc: 'Te lleva a otro lugar del mapa, lejos de los muertos. Dos usos.',
    color: '#f0a040',
    look: { shape: 'pico', cook: 'horno', fill: '#d8a870' },
  },
  {
    id: 'picante',
    sabor: 'Carne picante',
    name: 'Sin Chamuscar',
    kind: 'clasica',
    rarity: 'comun',
    level: 5,
    use: 'rondas',
    dur: 3,
    desc: 'Tus propias explosiones y el fuego no te hacen nada.',
    color: '#e0301e',
    look: { shape: 'trenza', cook: 'horno', mark: 'aji', fill: '#8a2a18' },
  },
  {
    id: 'tucumana',
    sabor: 'Tucumana',
    name: 'Manos Rápidas',
    kind: 'clasica',
    rarity: 'comun',
    level: 10,
    use: 'rondas',
    dur: 3,
    desc: 'Cebás, cambiás de mate y levantás a los compañeros mucho más rápido.',
    color: '#58a8e0',
    look: { shape: 'fino', cook: 'frita', fill: '#6a3a22', pleats: 13 },
  },
  {
    id: 'caprese',
    sabor: 'Caprese',
    name: 'Tiro y Corro',
    kind: 'clasica',
    rarity: 'comun',
    level: 16,
    use: 'tiempo',
    dur: 180,
    desc: 'Podés tirar mientras corrés.',
    color: '#3aa84a',
    look: { shape: 'redonda', cook: 'horno', mark: 'tomate', fill: '#e8e0d0' },
  },
  {
    id: 'arabe',
    sabor: 'Árabe',
    name: 'Plata en Balas',
    kind: 'clasica',
    rarity: 'comun',
    level: 22,
    use: 'tiempo',
    dur: 60,
    desc: 'Lo que ganás no va a los puntos: cada 10 te dan una bala para el mate que tenés en la mano.',
    color: '#d8b060',
    look: { shape: 'triangulo', cook: 'palida', fill: '#8a3a2a' },
  },
  {
    id: 'roquefort',
    sabor: 'Roquefort',
    name: 'Gusto a Más',
    kind: 'clasica',
    rarity: 'comun',
    level: 29,
    use: 'auto',
    dur: 1,
    desc: 'La próxima vez que caigas y te levanten (o te levante la Rosamorte), no perdés los perks.',
    color: '#6a90b8',
    look: { shape: 'bolsita', cook: 'horno', mark: 'cortes', fill: '#e8ecee' },
  },
  {
    id: 'fugazzeta',
    sabor: 'Cebolla y queso',
    name: 'Brasas',
    kind: 'clasica',
    rarity: 'comun',
    level: 37,
    use: 'auto',
    dur: 2,
    desc: 'Cuando un muerto te pega, largás una llamarada que quema a los de alrededor. Dos veces.',
    color: '#ff7a1a',
    look: { shape: 'bolsita', cook: 'horno', mark: 'queso', fill: '#f4e2b0' },
  },
  {
    id: 'verdura',
    sabor: 'Verdura',
    name: 'Prestada',
    kind: 'clasica',
    rarity: 'comun',
    level: 45,
    use: 'activa',
    dur: 2,
    secs: 60,
    desc: 'El mate que tenés en la mano pasa por el Pack-a-Pava por un minuto. Dos usos.',
    color: '#4a9a3a',
    look: { shape: 'sobre', cook: 'horno', fill: '#3a6a2a' },
  },

  // ---------------- especiales (se gastan) ----------------
  {
    id: 'cordero',
    sabor: 'Cordero patagónico',
    name: 'Vuelto',
    kind: 'especial',
    rarity: 'comun',
    use: 'activa',
    dur: 1,
    desc: 'Aparece una munición máxima.',
    color: '#8a6ad8',
    look: { shape: 'trenza', cook: 'barro', fill: '#5a2e1c' },
  },
  {
    id: 'cordobesa',
    sabor: 'Cordobesa (con azúcar)',
    name: 'Sin Asco',
    kind: 'especial',
    rarity: 'comun',
    use: 'activa',
    dur: 1,
    desc: 'Aparece una muerte instantánea.',
    color: '#8a6ad8',
    look: { shape: 'trenza', cook: 'horno', mark: 'azucar', fill: '#6a3a22' },
  },
  {
    id: 'matambre',
    sabor: 'Matambre a la pizza',
    name: 'Doble o Nada',
    kind: 'especial',
    rarity: 'comun',
    use: 'activa',
    dur: 1,
    desc: 'Aparecen los puntos dobles.',
    color: '#8a6ad8',
    look: { shape: 'pico', cook: 'horno', mark: 'queso', fill: '#b85a3a' },
  },
  {
    id: 'osobuco',
    sabor: 'Osobuco',
    name: 'Invierno Nuclear',
    kind: 'especial',
    rarity: 'comun',
    use: 'activa',
    dur: 1,
    desc: 'Aparece un Kaboom.',
    color: '#8a6ad8',
    look: { shape: 'trenza', cook: 'barro', mark: 'cortes', fill: '#4a2416' },
  },
  {
    id: 'calabaza',
    sabor: 'Calabaza y queso',
    name: 'Changarín',
    kind: 'especial',
    rarity: 'comun',
    use: 'activa',
    dur: 1,
    desc: 'Aparece un carpintero.',
    color: '#8a6ad8',
    look: { shape: 'redonda', cook: 'horno', mark: 'sesamo', fill: '#f09a2a' },
  },
  {
    id: 'bondiola',
    sabor: 'Bondiola braseada',
    name: 'Tiempo Regalado',
    kind: 'especial',
    rarity: 'comun',
    use: 'rondas',
    dur: 1,
    desc: 'Hasta que termine la ronda, los potenciadores duran el doble. Para todos.',
    color: '#8a6ad8',
    look: { shape: 'tenedor', cook: 'barro', mark: 'cortes', fill: '#6a3020' },
  },
  {
    id: 'espinaca',
    sabor: 'Espinaca y ricota',
    name: 'Cajón Bendito',
    kind: 'especial',
    rarity: 'comun',
    use: 'auto',
    dur: 1,
    desc: 'El próximo mate que saques de la caja sale del Pack-a-Pava.',
    color: '#8a6ad8',
    look: { shape: 'sobre', cook: 'horno', mark: 'sesamo', fill: '#4a7a3a' },
  },
  {
    id: 'riojana',
    sabor: 'Riojana',
    name: 'De la Pared',
    kind: 'especial',
    rarity: 'comun',
    use: 'auto',
    dur: 1,
    desc: 'El próximo mate que compres de la pared sale del Pack-a-Pava.',
    color: '#8a6ad8',
    look: { shape: 'fino', cook: 'horno', mark: 'aceituna', fill: '#6a3a22' },
  },
  {
    id: 'membrillo',
    sabor: 'Dulce de membrillo',
    name: 'La Yapa',
    kind: 'especial',
    rarity: 'comun',
    use: 'auto',
    dur: 1,
    desc: 'El próximo perk que te tomes viene con otro de yapa.',
    color: '#8a6ad8',
    look: { shape: 'tenedor', cook: 'frita', mark: 'azucar', fill: '#a8203a', small: true },
  },
  {
    id: 'patron',
    sabor: 'Criolla de carne suave',
    name: 'La del Patrón',
    kind: 'especial',
    rarity: 'rara',
    use: 'tiempo',
    dur: 600,
    desc: 'Por diez minutos ganás el doble de experiencia.',
    color: '#3a7ae8',
    look: { shape: 'trenza', cook: 'horno', mark: 'sesamo', fill: '#7a4a2a', big: true },
  },
  {
    id: 'mendocina',
    sabor: 'Mendocina',
    name: 'Paso de Tortuga',
    kind: 'especial',
    rarity: 'rara',
    level: 10,
    use: 'tiempo',
    dur: 60,
    desc: 'Por un minuto, todos los muertos caminan.',
    color: '#3a7ae8',
    look: { shape: 'trenza', cook: 'horno', mark: 'aceituna', fill: '#6a3a22' },
  },
  {
    id: 'atun',
    sabor: 'Atún (de vigilia)',
    name: 'Liquidación Total',
    kind: 'especial',
    rarity: 'rara',
    use: 'activa',
    dur: 1,
    desc: 'Aparece una liquidación.',
    color: '#3a7ae8',
    look: { shape: 'tenedor', cook: 'palida', mark: 'verdeo', fill: '#c8a878' },
  },
  {
    id: 'jabali',
    sabor: 'Jabalí',
    name: 'Ojos de Vidrio',
    kind: 'especial',
    rarity: 'rara',
    level: 12,
    use: 'activa',
    dur: 1,
    secs: 30,
    desc: 'Por 30 segundos, los muertos no ven a nadie.',
    color: '#3a7ae8',
    look: { shape: 'trenza', cook: 'barro', mark: 'aji', fill: '#4a2014' },
  },
  {
    id: 'cabrito',
    sabor: 'Cabrito',
    name: 'Cabezazo',
    kind: 'especial',
    rarity: 'rara',
    use: 'rondas',
    dur: 1,
    desc: 'Hasta que termine la ronda, cada tiro que pega va a la cabeza.',
    color: '#3a7ae8',
    look: { shape: 'fino', cook: 'barro', fill: '#5a2a1a' },
  },
  {
    id: 'charqui',
    sabor: 'Charqui',
    name: 'Chispazo',
    kind: 'especial',
    rarity: 'rara',
    use: 'auto',
    dur: 5,
    desc: 'Tus próximos cinco facones largan una descarga que electrocuta a los de alrededor.',
    color: '#3a7ae8',
    look: { shape: 'trenza', cook: 'barro', mark: 'cortes', fill: '#3a1a10' },
  },
  {
    id: 'mariscos',
    sabor: 'Mariscos',
    name: 'Invita la Casa',
    kind: 'especial',
    rarity: 'rara',
    use: 'activa',
    dur: 1,
    desc: 'Te tomás gratis un perk del mapa que no tenías.',
    color: '#3a7ae8',
    look: { shape: 'parada', cook: 'horno', mark: 'verdeo', fill: '#e8a888' },
  },
  {
    id: 'cuatroquesos',
    sabor: 'Cuatro quesos',
    name: 'Volado',
    kind: 'especial',
    rarity: 'rara',
    level: 15,
    use: 'activa',
    dur: 1,
    desc: 'Les revienta la cabeza a todos los muertos que tenés a la vista.',
    color: '#3a7ae8',
    look: { shape: 'bolsita', cook: 'horno', mark: 'queso', fill: '#f8eed0' },
  },
  {
    id: 'batata',
    sabor: 'Dulce de batata',
    name: 'Bombillón',
    kind: 'especial',
    rarity: 'rara',
    level: 18,
    use: 'activa',
    dur: 1,
    desc: 'Aparece la Máquina de Muerte.',
    color: '#3a7ae8',
    look: { shape: 'tenedor', cook: 'frita', mark: 'azucar', fill: '#8a2a3a', small: true },
  },
  {
    id: 'santiaguena',
    sabor: 'Santiagueña',
    name: 'Ronda Robada',
    kind: 'especial',
    rarity: 'ultra',
    level: 25,
    use: 'activa',
    dur: 1,
    desc: 'La ronda se termina al toque y cada uno se lleva 1600 puntos.',
    color: '#f0a020',
    look: { shape: 'fino', cook: 'horno', mark: 'verdeo', fill: '#6a3a22' },
  },
  {
    id: 'yacare',
    sabor: 'Yacaré',
    name: 'Todo Incluido',
    kind: 'especial',
    rarity: 'ultra',
    level: 35,
    use: 'auto',
    dur: 1,
    desc: 'Te tomás de una todos los perks del mapa.',
    color: '#f0a020',
    look: { shape: 'pico', cook: 'barro', mark: 'verdeo', fill: '#d8c8a0' },
  },
  {
    id: 'llama',
    sabor: 'Llama',
    name: 'Fiado',
    kind: 'especial',
    rarity: 'ultra',
    level: 30,
    use: 'tiempo',
    dur: 60,
    desc: 'Por un minuto, todo gratis: puertas, perks, la caja, la pared y el Pack-a-Pava.',
    color: '#f0a020',
    look: { shape: 'trenza', cook: 'barro', mark: 'sesamo', fill: '#4a2416' },
  },
  {
    id: 'surubi',
    sabor: 'Surubí',
    name: 'Llueven Premios',
    kind: 'especial',
    rarity: 'ultra',
    level: 40,
    use: 'activa',
    dur: 1,
    desc: 'Aparecen todos los potenciadores juntos.',
    color: '#f0a020',
    look: { shape: 'tenedor', cook: 'horno', mark: 'verdeo', fill: '#e8dcc0' },
  },
  {
    id: 'ciervo',
    sabor: 'Ciervo',
    name: 'Tiempo Muerto',
    kind: 'especial',
    rarity: 'ultra',
    level: 20,
    use: 'activa',
    dur: 1,
    secs: 20,
    desc: 'Los muertos se quedan quietos 20 segundos.',
    color: '#f0a020',
    look: { shape: 'trenza', cook: 'barro', mark: 'cortes', fill: '#3a1810' },
  },
];

export const EMPANADA = Object.fromEntries(EMPANADAS.map((e) => [e.id, e]));
export const CLASICAS = EMPANADAS.filter((e) => e.kind === 'clasica');
export const ESPECIALES = EMPANADAS.filter((e) => e.kind === 'especial');
export const RARITY = {
  comun: { name: 'Especial', color: '#8a6ad8' },
  rara: { name: 'Especial rara', color: '#3a7ae8' },
  ultra: { name: 'Especial ultra rara', color: '#f0a020' },
};

// La canasta de fábrica (sin armar): las primeras cinco clásicas que ya se tienen.
export const defaultCanasta = (isUnlocked) => CLASICAS.filter((e) => isUnlocked({ level: e.level })).slice(0, 5).map((e) => e.id);

// El horno cobra por ronda: la primera 500, la segunda 1000, la tercera 2000,
// y no da más hasta la próxima.
export const HORNO_COST = [500, 1000, 2000];
