// Arsenal matero. Los valores imitan el rol de cada arma de Black Ops 1:
// el daño está pensado contra las vidas de zombie de ese juego (150 en la
// ronda 1, +100 por ronda hasta la 9 y luego x1,1 por ronda).
//
// kind: 'hitscan' | 'projectile' | 'chain' | 'freeze' | 'blast' | 'bolt' | 'tactical'
// El modelo 3D de cada arma se arma en weapons/viewmodels.js con el mismo id.

export const WEAPONS = {
  porongo: {
    name: 'Mate Porongo',
    desc: 'El de toda la vida. Chico, confiable y siempre a mano.',
    kind: 'hitscan',
    auto: false,
    rpm: 450,
    mag: 8,
    reserve: 80,
    reload: 1.6,
    damage: 40,
    headMult: 3.5,
    spread: 0.022,
    range: 60,
    pen: 1,
    sound: 'pistol',
    recoil: 0.05,
    chalk: 'tall',
    pap: {
      name: 'Porongo Explosivo',
      kind: 'projectile',
      projectile: { speed: 42, gravity: 9, radius: 3.2, damage: 900, color: 0xffa040, size: 0.09, trail: 0xffc070 },
      mag: 12,
      reserve: 60,
      damage: 900,
      rpm: 420,
      sound: 'launcher',
    },
  },
  madera: {
    name: 'Mate de Palo Santo',
    desc: 'Madera perfumada tallada a mano. Un tiro, un problema menos.',
    kind: 'hitscan',
    auto: false,
    rpm: 520,
    mag: 8,
    reserve: 96,
    reload: 2.2,
    damage: 105,
    headMult: 3.5,
    spread: 0.02,
    range: 90,
    pen: 2,
    sound: 'rifle',
    recoil: 0.08,
    chalk: 'cyl',
    wall: 500,
    pap: { name: 'Mate de Quebracho', damage: 190, mag: 12, reserve: 144, auto: true, rpm: 600 },
  },
  plastico: {
    name: 'Mate de Plástico',
    desc: 'Mate malo, doble bombilla. Da vergüenza pero te salva.',
    kind: 'hitscan',
    auto: false,
    rpm: 300,
    mag: 2,
    reserve: 38,
    reload: 2.6,
    damage: 55,
    pellets: 8,
    headMult: 1.8,
    spread: 0.09,
    range: 22,
    pen: 1,
    sound: 'shotgun',
    recoil: 0.16,
    chalk: 'cup',
    chalkStraws: 2,
    wall: 500,
    pap: { name: 'Mate del Diablo', damage: 120, mag: 4, reserve: 60, burn: true },
  },
  vidrio: {
    name: 'Mate de Vidrio',
    desc: 'Se ve la yerba adentro. Escupe agua caliente a lo loco.',
    kind: 'hitscan',
    auto: true,
    rpm: 800,
    mag: 30,
    reserve: 120,
    reload: 2.3,
    damage: 65,
    headMult: 3,
    spread: 0.035,
    range: 45,
    pen: 1,
    sound: 'smg',
    recoil: 0.025,
    chalk: 'cup',
    wall: 1000,
    pap: { name: 'Mate de Cristal Tallado', damage: 130, mag: 40, reserve: 200, rpm: 900 },
  },
  lata: {
    name: 'Mate de Lata',
    desc: 'Aluminio de camping, bombilla gruesa. Para abrir camino.',
    kind: 'hitscan',
    auto: false,
    rpm: 70,
    mag: 6,
    reserve: 54,
    reload: 0.55,
    shellReload: true,
    damage: 85,
    pellets: 8,
    headMult: 1.8,
    spread: 0.07,
    range: 26,
    pen: 2,
    sound: 'pump',
    recoil: 0.18,
    chalk: 'cyl',
    wall: 1500,
    pap: { name: 'Latón Fulminante', damage: 170, mag: 10, reserve: 80, rpm: 110 },
  },
  algarrobo: {
    name: 'Mate de Algarrobo',
    desc: 'Ráfaga corta y madera dura. Pega como patada de mula.',
    kind: 'hitscan',
    auto: true,
    rpm: 700,
    mag: 20,
    reserve: 160,
    reload: 2.4,
    damage: 95,
    headMult: 3,
    spread: 0.03,
    range: 55,
    pen: 1,
    sound: 'smg',
    recoil: 0.03,
    chalk: 'tall',
    wall: 1200,
    pap: { name: 'Algarrobo Milenario', damage: 170, mag: 40, reserve: 280 },
  },
  imperial: {
    name: 'Mate Imperial',
    desc: 'Calabaza con virola de alpaca cincelada. Elegancia automática.',
    kind: 'hitscan',
    auto: true,
    rpm: 720,
    mag: 30,
    reserve: 240,
    reload: 2.7,
    damage: 150,
    headMult: 3.2,
    spread: 0.025,
    range: 80,
    pen: 2,
    sound: 'rifle',
    recoil: 0.035,
    box: 10,
    pap: { name: 'Imperial de Oro y Plata', damage: 240, mag: 45, reserve: 360, rpm: 780 },
  },
  camionero: {
    name: 'Mate Camionero',
    desc: 'Para la ruta larga: forrado en cuero, entra medio kilo de yerba.',
    kind: 'hitscan',
    auto: true,
    rpm: 750,
    mag: 100,
    reserve: 400,
    reload: 4.4,
    damage: 130,
    headMult: 2.8,
    spread: 0.04,
    range: 75,
    pen: 3,
    sound: 'lmg',
    recoil: 0.04,
    moveMult: 0.88,
    box: 10,
    pap: { name: 'Camionero de Larga Distancia', damage: 210, mag: 150, reserve: 600 },
  },
  torpedo: {
    name: 'Mate Torpedo',
    desc: 'Calabaza alargada con mira. Un sorbo, una cabeza.',
    kind: 'hitscan',
    auto: false,
    rpm: 55,
    mag: 5,
    reserve: 50,
    reload: 3.1,
    damage: 800,
    headMult: 5,
    spread: 0.06,
    adsSpread: 0,
    range: 160,
    pen: 4,
    sound: 'sniper',
    recoil: 0.25,
    scope: true,
    adsFov: 22,
    box: 8,
    pap: {
      name: 'Torpedo Nuclear',
      damage: 1600,
      mag: 8,
      reserve: 64,
      explosive: { radius: 3, damage: 1000 },
    },
  },
  silicona: {
    name: 'Mate de Silicona',
    desc: 'Mate malo. Se dobla, se tuerce y apunta a cualquier lado.',
    kind: 'hitscan',
    auto: true,
    rpm: 950,
    mag: 40,
    reserve: 200,
    reload: 2.2,
    damage: 28,
    headMult: 2,
    spread: 0.075,
    range: 30,
    pen: 1,
    sound: 'bad',
    recoil: 0.02,
    wobble: true,
    box: 8,
    pap: { name: 'Silicona Industrial', damage: 75, mag: 60, reserve: 300 },
  },
  cocido: {
    name: 'Mate Cocido',
    desc: 'Esto ni siquiera es mate. Tira saquitos. Lo siento mucho.',
    kind: 'projectile',
    auto: false,
    rpm: 220,
    mag: 10,
    reserve: 60,
    reload: 2.0,
    damage: 70,
    headMult: 1.5,
    range: 40,
    sound: 'bad',
    recoil: 0.04,
    projectile: { speed: 22, gravity: 6, radius: 0, damage: 70, color: 0xd8c9a8, size: 0.07, teabag: true },
    box: 6,
    pap: {
      name: 'Mate Cocido con Leche',
      damage: 220,
      mag: 16,
      reserve: 96,
      projectile: { speed: 30, gravity: 4, radius: 1.4, damage: 220, color: 0xfff6e0, size: 0.08, teabag: true },
    },
  },
  bombillazo: {
    name: 'Bombillazo',
    desc: 'Dispara la bombilla. Se clava y explota. Sí, perdés la bombilla.',
    kind: 'bolt',
    auto: false,
    rpm: 60,
    mag: 1,
    reserve: 12,
    reload: 1.9,
    damage: 1200,
    headMult: 1,
    range: 80,
    sound: 'bolt',
    recoil: 0.12,
    bolt: { speed: 55, fuse: 1.6, radius: 3.2, damage: 1400 },
    box: 6,
    pap: {
      name: 'Bombillazo Mágico',
      reserve: 16,
      bolt: { speed: 65, fuse: 3.2, radius: 4, damage: 3000, lure: true },
    },
  },
  rayo: {
    name: 'Rayo Matero',
    desc: 'Tecnología del Abuelo: agua verde a 115 grados.',
    kind: 'projectile',
    auto: false,
    rpm: 190,
    mag: 20,
    reserve: 160,
    reload: 3.2,
    damage: 1000,
    headMult: 1,
    range: 120,
    sound: 'ray',
    recoil: 0.07,
    special: true,
    projectile: { speed: 60, gravity: 0, radius: 2.8, damage: 1000, splash: 320, color: 0x6dff7a, size: 0.16, glow: true, selfDamage: 25 },
    box: 3,
    pap: {
      name: 'Rayo Matero Mark II',
      mag: 40,
      reserve: 200,
      rpm: 260,
      projectile: { speed: 70, gravity: 0, radius: 3.2, damage: 1800, splash: 600, color: 0xff3a3a, size: 0.18, glow: true, selfDamage: 25 },
    },
  },
  wunder: {
    name: 'Wunder-Mate DG-2',
    desc: 'La bombilla es una bobina de Tesla. Electrocuta en cadena.',
    kind: 'chain',
    auto: false,
    rpm: 70,
    mag: 3,
    reserve: 9,
    reload: 3.6,
    damage: 100000,
    headMult: 1,
    range: 36,
    sound: 'tesla',
    recoil: 0.2,
    special: true,
    chain: { targets: 10, hop: 7 },
    box: 2,
    pap: { name: 'Wunder-Mate DG-3 JZ', mag: 6, reserve: 18, chain: { targets: 24, hop: 9 } },
  },
  terere: {
    name: 'Tereré de Invierno',
    desc: 'Guampa con hielo y limón. Congela todo lo que toca.',
    kind: 'freeze',
    auto: false,
    rpm: 160,
    mag: 6,
    reserve: 30,
    reload: 2.8,
    damage: 100000,
    headMult: 1,
    range: 13,
    sound: 'ice',
    recoil: 0.1,
    special: true,
    cone: { angle: 0.32, targets: 6 },
    box: 2,
    pap: { name: 'Tereré del Polo Sur', mag: 9, reserve: 45, range: 17, cone: { angle: 0.45, targets: 10 } },
  },
  tronador: {
    name: 'Mate Tronador',
    desc: 'Un soplido que manda zombies a Misiones.',
    kind: 'blast',
    auto: false,
    rpm: 60,
    mag: 2,
    reserve: 12,
    reload: 3.2,
    damage: 100000,
    headMult: 1,
    range: 11,
    sound: 'thunder',
    recoil: 0.45,
    special: true,
    cone: { angle: 0.55, targets: 30 },
    moveMult: 0.9,
    box: 2,
    pap: { name: 'Tronador Cero Absoluto', mag: 4, reserve: 24, range: 14 },
  },
  pava: {
    name: 'Pava Silbadora',
    desc: 'Tirala: silba, los zombies van a ver quién ceba y... ¡bum!',
    kind: 'tactical',
    count: 3,
    box: 5,
  },
  oro: {
    name: 'Mate de Oro del Abuelo',
    desc: 'El premio del Abuelo. Convierte zombies en yerba.',
    kind: 'projectile',
    auto: true,
    rpm: 360,
    mag: 50,
    reserve: 500,
    reload: 2,
    damage: 5000,
    headMult: 1,
    range: 120,
    sound: 'ray',
    recoil: 0.05,
    special: true,
    projectile: { speed: 80, gravity: 0, radius: 2.4, damage: 5000, splash: 1500, color: 0xffd34a, size: 0.14, glow: true },
    pap: { name: 'Mate de Oro Macizo', mag: 80, reserve: 800 },
  },
};

// Pesos de la caja misteriosa (0 o ausente = no sale de la caja).
export const BOX_POOL = Object.entries(WEAPONS)
  .filter(([id, w]) => w.box || (w.wall && id !== 'porongo'))
  .map(([id, w]) => ({ id, weight: w.box || 7 }));

export const KNIFE = { damage: 150, range: 1.8, time: 0.55, lunge: 3 };
export const GRENADE = { damage: 400, radius: 5.5, fuse: 2.2, max: 4, perRound: 2, wall: 250 };

// Arma efectiva: datos base mezclados con los del Pack-a-Pava si corresponde.
export function weaponStats(id, upgraded) {
  const base = WEAPONS[id];
  if (!upgraded || !base.pap) return { id, upgraded: false, ...base };
  const { pap } = base;
  return {
    id,
    upgraded: true,
    ...base,
    ...pap,
    projectile: pap.projectile || base.projectile,
    bolt: pap.bolt || base.bolt,
    chain: pap.chain || base.chain,
    cone: pap.cone || base.cone,
    reload: base.reload * 0.85,
  };
}
