// Perks: máquinas con forma de paquete gigante de yerba. Cada una imita el
// paquete de una yerba mítica (colores y estilo), con una marca en joda.

export const PERKS = {
  jugg: {
    name: 'Juggernog',
    cost: 2500,
    color: '#c8202a',
    glyph: '♥',
    desc: 'Aguantás el doble de golpes.',
    label: {
      brand: 'Taragüerno',
      tagline: 'LA DEL PALO FUERTE · DESDE 1924',
      bg: '#b3151d',
      band: '#fbf3e4',
      bandText: '#b3151d',
      accent: '#f3c233',
      leaf: 'rgba(255,255,255,0.12)',
      text: '#fff7ea',
    },
  },
  revive: {
    name: 'Quick Revive',
    cost: 1500,
    soloCost: 500,
    color: '#39a8e0',
    glyph: '✚',
    desc: 'Si caés, te levantás solo (3 veces).',
    coopDesc: 'Levantás a tus compañeros al doble de rápido.',
    label: {
      brand: 'Rosamorte',
      tagline: 'SABOR FUERTE PARA VOLVER',
      bg: '#f0b52c',
      band: '#c1271d',
      bandText: '#fff5dc',
      accent: '#c1271d',
      leaf: 'rgba(120,40,10,0.18)',
      text: '#3a1a08',
      brandColor: '#c1271d',
      stroke: 'rgba(255,240,200,0.8)',
    },
  },
  speed: {
    name: 'Speed Cola',
    cost: 3000,
    color: '#3dbb3a',
    glyph: '»',
    desc: 'Recargás el doble de rápido.',
    label: {
      brand: 'Rapidito',
      tagline: 'SUAVE, RÁPIDA Y SIN VUELTAS',
      bg: '#f6ecd0',
      band: '#1e4f9c',
      bandText: '#ffe36b',
      accent: '#d4282c',
      leaf: 'rgba(30,79,156,0.12)',
      text: '#1e4f9c',
      brandColor: '#d4282c',
      stroke: 'rgba(255,255,255,0.9)',
    },
  },
  doubletap: {
    name: 'Double Tap',
    cost: 2000,
    color: '#e8a21c',
    glyph: '✠',
    desc: 'Disparás más rápido.',
    label: {
      brand: 'Doble Cruz',
      tagline: 'DOS CRUCES · EL DOBLE DE BALA',
      bg: '#1f6a3a',
      band: '#f2e9d2',
      bandText: '#b41f24',
      accent: '#b41f24',
      leaf: 'rgba(255,255,255,0.1)',
      text: '#fff4dc',
    },
  },
  mule: {
    name: 'Mule Kick',
    cost: 4000,
    color: '#6f9a3a',
    glyph: '⚑',
    desc: 'Podés llevar un tercer mate.',
    label: {
      brand: 'Mulanda',
      tagline: 'CON PALO, CON TODO Y CON UN MATE MÁS',
      bg: '#e9e1cf',
      band: '#6b3e1f',
      bandText: '#f7e7b0',
      accent: '#3d7a2c',
      leaf: 'rgba(61,122,44,0.25)',
      text: '#2f4a1c',
      brandColor: '#3d7a2c',
      stroke: 'rgba(255,255,255,0.8)',
    },
  },
  deadshot: {
    name: 'Deadshot Daiquiri',
    cost: 1500,
    color: '#1a1a1a',
    glyph: '☼',
    desc: 'No hace absolutamente nada.',
    label: {
      brand: 'Nadarias',
      tagline: 'LA YERBA URUGUAYA QUE NO HACE NADA',
      bg: '#f5cf1f',
      band: '#1b3f8f',
      bandText: '#ffffff',
      accent: '#d82320',
      leaf: 'rgba(216,35,32,0.18)',
      text: '#1b3f8f',
      brandColor: '#d82320',
      brandSize: 100,
      stroke: 'rgba(255,255,255,0.9)',
    },
  },
};

export const PERK_ORDER = ['jugg', 'revive', 'speed', 'doubletap', 'mule', 'deadshot'];
